---
# This workflow run a job on `pull_request`.
#
# `Terraform Docs - Generate` job use GitHub Action `terraform-docs/gh-actions` to create README.md file.
#   Documentation
#     - https://github.com/marketplace/actions/terraform-docs-gh-actions

name: "Terraform Docs - Generate - Pull Request"

on:  # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - '*'                      # matches every branch that doesn't contain a '/'
      - '*/*'                    # matches every branch containing a single '/'
      - '**'                     # matches every branch

permissions:
  contents: write

jobs:
  terraform-docs:
    name: "Terraform Docs - Generate"
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Render terraform docs inside the README.md and push changes back to PR branch
        uses: terraform-docs/gh-actions@v1.0.0
        with:
          config-file: .github/terraform-docs/.tfdocs-config.yml
          git-push: "true"
          output-format: "markdown document"
          working-dir: .
